export default {
  login: 'tmgAzit',
  id: 53204583,
  node_id: 'MDQ6VXNlcjUzMjA0NTgz',
  avatar_url: 'https://avatars.githubusercontent.com/u/53204583?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/tmgAzit',
  html_url: 'https://github.com/tmgAzit',
  followers_url: 'https://api.github.com/users/tmgAzit/followers',
  following_url: 'https://api.github.com/users/tmgAzit/following{/other_user}',
  gists_url: 'https://api.github.com/users/tmgAzit/gists{/gist_id}',
  starred_url: 'https://api.github.com/users/tmgAzit/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/tmgAzit/subscriptions',
  organizations_url: 'https://api.github.com/users/tmgAzit/orgs',
  repos_url: 'https://api.github.com/users/tmgAzit/repos',
  events_url: 'https://api.github.com/users/tmgAzit/events{/privacy}',
  received_events_url: 'https://api.github.com/users/tmgAzit/received_events',
  type: 'User',
  site_admin: false,
  name: 'Ajit Ghising',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 62,
  public_gists: 0,
  followers: 7,
  following: 9,
  created_at: '2019-07-23T03:23:28Z',
  updated_at: '2022-05-20T06:36:08Z',
};
//   {
//   login: 'john-smilga',
//   id: 42133389,
//   node_id: 'MDQ6VXNlcjQyMTMzMzg5',
//   avatar_url: 'https://avatars3.githubusercontent.com/u/42133389?v=4',
//   gravatar_id: '',
//   url: 'https://api.github.com/users/john-smilga',
//   html_url: 'https://github.com/john-smilga',
//   followers_url: 'https://api.github.com/users/john-smilga/followers',
//   following_url:
//     'https://api.github.com/users/john-smilga/following{/other_user}',
//   gists_url: 'https://api.github.com/users/john-smilga/gists{/gist_id}',
//   starred_url:
//     'https://api.github.com/users/john-smilga/starred{/owner}{/repo}',
//   subscriptions_url: 'https://api.github.com/users/john-smilga/subscriptions',
//   organizations_url: 'https://api.github.com/users/john-smilga/orgs',
//   repos_url: 'https://api.github.com/users/john-smilga/repos',
//   events_url: 'https://api.github.com/users/john-smilga/events{/privacy}',
//   received_events_url:
//     'https://api.github.com/users/john-smilga/received_events',
//   type: 'User',
//   site_admin: false,
//   name: 'John Smilga',
//   company: 'Coding Addict',
//   blog: 'www.johnsmilga.com',
//   location: 'Los Angeles',
//   email: null,
//   hireable: null,
//   bio: 'Creator of Coding Addict',
//   twitter_username: 'john_smilga',
//   public_repos: 152,
//   public_gists: 0,
//   followers: 1495,
//   following: 0,
//   created_at: '2018-08-06T06:48:23Z',
//   updated_at: '2020-07-08T05:01:32Z',
// };
